name: Ederson Corbari
description: Things about software development
meta_description: "Ederson Corbari Site, Blogging about software development"

markdown: kramdown
highlighter: rouge
#highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'https://edersoncorbari.github.io/'
google_analytics: 'UA-100481195-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url: 'https://edersoncorbari.github.com/'
author: 'Ederson de Moura Corbari'

urls:
    about: /about

